# Generated by Django 5.1.1 on 2024-09-14 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automovel', '0001_initial'),
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('codigo_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('chassi_automovel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='automovel.automovel')),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cliente.cliente')),
                ('username_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
