# Generated by Django 5.1.1 on 2024-09-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_venda_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='chassi_automovel',
            field=models.CharField(max_length=17),
        ),
    ]
